# Generated by Django 5.0.3 on 2024-03-25 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
