# Generated by Django 5.0.3 on 2024-03-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(blank=True, default='default_picture.jpg', null=True, upload_to='channel_pictures/'),
        ),
    ]
