# Generated by Django 5.0.3 on 2024-04-04 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reactions',
        ),
        migrations.AlterField(
            model_name='thread',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='thread_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.TextField(blank=True),
        ),
    ]
