# Generated by Django 5.0.3 on 2024-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_channel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='channel_pictures/'),
        ),
    ]
