# Generated by Django 5.0.3 on 2024-04-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
