# Generated by Django 5.0.3 on 2024-04-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='reactions',
        ),
        migrations.AddField(
            model_name='thread',
            name='reactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
